### PR TITLE
Fix token rotation

### PR DESCRIPTION
**Pull request by rashboldb**
### 🛠 Changes being made
This is a quick fix for the token rotation. The module itself was working, but the changes being made by it did not translate to the host. So this makes a docker volume out of the .env file.

### 🧪 How was it tested? / Demo

Tested by leaving the container running for 12h+ and restarting it after that.
### 🏎 Quality check

- [ ]  Set base branch to main.
- [x]  Pull request is prepared: Added to sprint, added yourself as assignee, reviewers are added.
- [x]  PR is not very big (about 200 lines of change ideally).
- [x]  I have added comments to my code, particularly in hard-to-understand areas.
- [x]  Doesn't create any new FIXME or TODO comments. If not, please explain.
- [x]  Tested manually (explained the scenario, added screenshots)
- [x]  I have tested my changes locally before pushing them to this branch.
- [x]  I have updated the documentation accordingly.
- [x]  Followed best practice rules:https://google.github.io/styleguide/pyguide.html

### CODE REVIEW

**Comment by iramykytyn** [comment]
let me run it and approve if it works for me!

**Comment by iramykytyn** [comment]
@rashboldb do we need to add refresh token to env file?

**Comment by rashboldb** [comment]
> @rashboldb do we need to add refresh token to env file?

yes, we do

**Comment by iramykytyn** [comment]
I see it working after the container restarted and rebuilt 12 hours after the start. Good job!

**Review by iramykytyn — APPROVED** [review]
I see it working after the container restarted and rebuilt 12 hours after the start. Good job!

**Pull request merged**
