### PR TITLE
Add module to extract cv data

### PR DESCRIPTION
**Pull request by Zhornovyi**
### 🛠 Changes being made

ISSUE: https://github.com/COXIT-CO/CVScanAI/issues/11

Its a python module we can use to extract the data from the CV, and then save it to the database.

As output we will have pydantic model with a list of fields:
- email
- full_name
- summary
-  skills
- education
- experience (in years)

### 🏎 Quality check

- [ ]  Set base branch to main.
- [ ]  Pull request is prepared: Added to sprint, added yourself as assignee, reviewers are added.
- [ ]  PR is not very big (about 200 lines of change ideally).
- [ ]  I have added comments to my code, particularly in hard-to-understand areas.
- [ ]  Doesn't create any new FIXME or TODO comments. If not, please explain.
- [ ]  Tested manually (explained the scenario, added screenshots)
- [ ]  I have tested my changes locally before pushing them to this branch.
- [ ]  I have updated the documentation accordingly.
- [ ]  Followed best practice rules:https://google.github.io/styleguide/pyguide.html

### CODE REVIEW

**Review by iramykytyn — CHANGES_REQUESTED** [review]
For PR to be ready to merge it should be clear how to run it, it should be well documented, and tested if possible.

For this PR the following things should be done:
- Native OpenAI library should be used instead of langchain.
- Add unit tests for this module to cover CV parsing. 
- Add readme to specify what is expected input/output and how to run it.
- Doc strings could be more informative.
- `Candidate(BaseModel):` - not clear what is BaseModel class for. `Candidate` name is not descriptive. It looks like data class without any method so `CandidateData`, or `CandidateInfo` would be more clear whats tehpurpose of the class. Please explain this part if there is any reason for such structure.

I would put all candidate info extraction logic into one file called "extract_candidate_info.py". Separately I would created openai_api.py file and implemented class OpenaiAPI which could have all the logic to read openai configuration and chat method which should basically implement the logic to take system prompt and messages as an input and call chat/completion API. It should parse endpoint response and return it to the client who called it. 
We need to have openai logic decoupled to be able to reuse it in other modules.

All the examples code shoudl be separated from source code in some sample_app directory, or in tests directory.

**Comment by Zhornovyi** [comment]
1. Readme is updated
2. Doc strings is more informative now
3. Native OpenAI we can't be  integrated currently, we use `kor` library that expect langchain chat model generating  the promt from the pydantic model
4. Candidate is a pydantic model that should be inherited from pydantic.BaseModel.

**Comment by Zhornovyi** [comment]
⚠️   PR contains some changes from #22. So please merge this PR after it

**Comment by iramykytyn** [comment]
Converting this PR to draft for now since we need to investigate if hardcoded prompt will work for all resumes structures and the proposed file structure should be revisited after recent changes in the repo.
For the future, it's better to have prompt configurable from the config file, so we easily update it if needed.
I still think that native OpenAI is enough for this task, so no need to use the langchain here. 

I recommend covering this PR with test cases instead of a sample app. Tests should read prompt from config, use few PDF samples, and check if the result will be expected json. This would automatically implemented #26.

**Pull request closed without merging**
